name: MY First workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome message
          run: echo "My First github workflows"

        - name: List files
          run: ls

        - name: Read file
          run: cat README.md
